### ISSUE TITLE
Reproducing Aesthetic Quality results from paper

### ISSUE THREAD

**Issue by ritiztambi** [yk7333/d3po#4]
I'm trying to reproduce aesthetic quality results from paper on simple animals prompts on a 4 GPU node.
Sampling and training params have been kept the same apart from learning rate at 3e-5 (taken from paper appendix). 

Results seem to show disintegration
<img width="773" alt="Screenshot 2023-12-14 at 8 48 47 AM" src="https://github.com/yk7333/d3po/assets/17811168/46bfd63b-4713-414e-af17-d876c8eb6ea1">
<img width="1580" alt="Screenshot 2023-12-14 at 8 49 11 AM" src="https://github.com/yk7333/d3po/assets/17811168/c694d60d-6245-473a-b40b-f403b98d63ea">

A few questions I had
1. Any more adjustments to be made in params?
2. Is d3po in general very sensitive to parameters and is that data specific?

**Comment by yk7333** [comment]
Thank you for your attention to our work. Upon further inspection, I found that there was indeed an issue with the previous version of the submitted code. The clamp operation for the ratio should be between 0.9 and 1.1 to prevent significant differences between the old and new policies. The previous code specified a range of 0.8 to 1.2, and the values saved on *WandB* were the maximum reward. We have now updated our code. The training curve is as follows:
![image](https://github.com/yk7333/d3po/assets/72459814/2da7b9b8-6590-4c6e-9191-9d32e0059aa4)
Regarding the issue you mentioned about image disintegration, we have also encountered this situation during experiments. A viable solution is to reduce the **train.eps** value in the config file or try lowering the learning rate to ensure that the differences between the old and new policies are not too large. D3PO is not data-specific; you can experiment with other prompts (such as *imagenet_animals*), and similar effects should be observed. However, we have not conducted in-depth experiments on parameter sensitivity. If you find image disintegration occurring with your dataset, you can try the aforementioned approaches of reducing the learning rate and **train.eps** value.

**Comment by yk7333** [comment]
The code for quantitative experiments of D3PO, DDPO, DPOK, and other methods has now been updated. Additionally, the curve plots from our paper's training have been updated as well. You can train and replicate the results using the new code by running the script `accelerate launch scripts/rm/train_d3po.py`. This should include successfully replicating experiments such as the Aesthetic Quality experiment you mentioned.
