### ISSUE TITLE
Releasing human preference data

### ISSUE THREAD

**Issue by vishaal27** [yk7333/d3po#8]
Hey, 
Thanks for your great work and for releasing your code publicly. I am very interested in the human evaluation data that you show in Fig 7 of the paper. Is it possible for you to release the exact prompts, image-pairs and raw human preferences that you collected for plotting Fig 7? This would be super helpful, thanks!

**Comment by yk7333** [comment]
Thank you for your interest in our work! In response to your needs, we have made the human evaluation data, prompts, images, and visualization code available on Hugging Face. You can access them at https://huggingface.co/datasets/yangkaiSIGS/d3po_datasets/

**Comment by vishaal27** [comment]
Amazing, thanks for your prompt response!
